notifications:
webhooks: http://requestb.in/xr28imxr
 on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always
    on_start: [always|never|change] # default: always
